### ISSUE TITLE
--password flag is nonfunctional

### ISSUE THREAD

**Issue by rtertiaer** [ttacon/meek#2]
The --password flag is nonfunctional. When used, this issue presents itself like so:

```
$ meek --password redacted -h db0.importantproject.lowhangingfru.it -u root
flag provided but not defined: -password
```

**Comment by ttacon** [comment]
Fixed by 476ad2292d09f765d73637ed7b47450cdbc02c3f, thanks! Was trying something tricky with the flag package and didn't test it _facepalm_.
